import qualified Options.Applicative as OA
import qualified Data.Text as T
import DuplicateScorer.Scoring
    ( FileWithReason(..)
    , ScoringFunction
    , selectBestFile
    , pathLengthScore
    , modificationTimeScore
    , pathDepthScore
    , createGoldenScore
    , createTrashScore
    )
import System.Process (showCommandForUser)

type FileGroup = [FilePath]

data ScorerOptions = ScorerOptions
    { goldenDirs :: [String]
    , trashDirs :: [String]
    } deriving (Show, Eq)

parseOptions :: OA.Parser ScorerOptions
parseOptions = ScorerOptions
    <$> OA.many (OA.strOption
        ( OA.long "golden"
       <> OA.short 'g'
       <> OA.metavar "DIR"
       <> OA.help "Golden directory pattern (can be specified multiple times)"))
    <*> OA.many (OA.strOption
        ( OA.long "trash"
       <> OA.short 't'
       <> OA.metavar "DIR"
       <> OA.help "Trash directory pattern (can be specified multiple times)"))

optsParser :: OA.ParserInfo ScorerOptions
optsParser = OA.info (parseOptions OA.<**> OA.helper)
    ( OA.fullDesc
   <> OA.progDesc "Score duplicate files and select the best one to keep"
   <> OA.header "duplicate-file-scorer - intelligently choose which duplicate file to keep")

data ScoredGroup = ScoredGroup
    { keepFile :: FileWithReason      -- ^ The file to keep
    , removeFiles :: [FileWithReason]  -- ^ Files to remove
    } deriving (Show, Eq)

-- Parse stdin into groups of files
-- Empty lines separate groups
parseFileGroups :: String -> [FileGroup]
parseFileGroups input =
    let allLines = lines input
        grouped = groupByEmpty allLines
    in grouped
  where
    groupByEmpty :: [String] -> [[String]]
    groupByEmpty [] = []
    groupByEmpty ls =
        let (group, rest) = break null ls
        in if null group
           then groupByEmpty (drop 1 rest)  -- Skip empty line and continue
           else group : groupByEmpty (drop 1 rest)

buildScoringFunctions :: ScorerOptions -> [ScoringFunction]
buildScoringFunctions opts =
    goldenScores ++ trashScores ++ baseScores
  where
    goldenScores = map (createGoldenScore . T.pack) (goldenDirs opts)
    trashScores = map (createTrashScore . T.pack) (trashDirs opts)
    baseScores = [modificationTimeScore, pathDepthScore, pathLengthScore]

scoreFileGroup :: [ScoringFunction] -> FileGroup -> IO ScoredGroup
scoreFileGroup _ [] = error "Cannot score empty file group"
scoreFileGroup _ [singleFile] =
    return $ ScoredGroup
        (FileWithReason singleFile "only file in group")
        []
scoreFileGroup scoringFns files = do
    (winner, losers) <- selectBestFile scoringFns files
    return $ ScoredGroup winner losers

printScoredGroupAsBash :: ScoredGroup -> IO ()
printScoredGroupAsBash group = do
    putStrLn $ "# KEEP:"
    putStrLn $ "#  " ++ reasonFilePath (keepFile group)
    putStrLn $ "#  (" ++ whyChosen (keepFile group) ++ ")"
    putStrLn $ "# REMOVE:"
    mapM_ printRemoveCommand (removeFiles group)
    putStrLn ""
  where
    printRemoveCommand file =
        let command = showCommandForUser "rm" ["-v", reasonFilePath file]
            comment = "  #" ++ whyChosen file
        in do
            putStrLn $ command ++ comment

main :: IO ()
main = do
    opts <- OA.execParser optsParser

    -- Read all content from stdin
    content <- getContents

    -- Score groups
    let fileGroups = parseFileGroups content
    let scoringFns = buildScoringFunctions opts
    scoredGroups <- mapM (scoreFileGroup scoringFns) fileGroups

    -- Print results as bash commands
    putStrLn "#!/bin/bash"
    putStrLn "# Generated by duplicate-file-scorer"
    putStrLn ""
    mapM_ printScoredGroupAsBash scoredGroups
